BoxLayout:
    orientation: 'vertical'
    padding: 20
    spacing: 10

    Button:
        text: 'Clear'
        on_press: app.handle_clear()

    TextInput:
        id: input_name
        text: ''
        multiline: False
        font_size: 24
        padding_y: [10, 10]

    Button:
        text: 'Greet'
        on_press: app.handle_greet()

    Label:
        id: output_label
        text: 'Enter your name'
        color: (1, 1, 0, 1)     # yellow
        font_size: 28